#config/local-development.yaml
services:
  collector:
    vault-path: stormsync/collector/local-development
    interval: 10s
  kafka:
    host: kafka-1
    port: 9092
    topic: raw-weather-report
  redis:
    host: redis
    port: 6379
    user: redis_user
    password: redis_password
    db: 0
  vault:
    protocol: http
    host: 192.168.1.100
    port: 8200